controller_list:
  - name: fake_kr3_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
initial:  # Define initial robot poses per group
  - group: kr3
    pose: init_pose